apiVersion: v1
kind: ConfigMap
metadata:
  name: snaplink-config
  namespace: {{ .Values.namespace }}
data:
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:$(POSTGRES_PASSWORD)@postgres:5432/{{ .Values.postgres.db }}"
  REDIS_URL: "redis://redis:6379"
