name: CI - Build, Scan, Push

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend, worker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          push: false
          load: true
          tags: jananiupeksha/snaplink-${{ matrix.service }}:${{ steps.vars.outputs.sha_short }}

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: jananiupeksha/snaplink-${{ matrix.service }}:${{ steps.vars.outputs.sha_short }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Push image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            jananiupeksha/snaplink-${{ matrix.service }}:${{ steps.vars.outputs.sha_short }}
            jananiupeksha/snaplink-${{ matrix.service }}:latest

  update-gitops:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repo (to read commit SHA)
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Clone GitOps repo
        run: git clone https://${{ secrets.GITOPS_PAT }}@github.com/JananiUpeksha/SnapLink-GitOps.git gitops-repo

      - name: Update image tags in values.yaml
        working-directory: gitops-repo/snaplink-chart
        run: |
          sed -i "s/tag: .*/tag: ${{ steps.vars.outputs.sha_short }}/" values.yaml
          cat values.yaml

      - name: Commit and push changes
        working-directory: gitops-repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add snaplink-chart/values.yaml
          git commit -m "Update image tags to ${{ steps.vars.outputs.sha_short }}" || echo "No changes to commit"
          git push origin main
